# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.6.0"

default_platform :ios

platform :ios do

  # 1
  desc "Creating a code signing certificate and provisioning profile"
  # 2
  lane :provision do
    # 3
    produce(
      app_name: 'CircleCI-iOS-TestFlightr',
      language: 'English',
      app_version: '1.0',
      sku: 'com.vironit.CircleTest-sku'
    )
    # 4
    cert
    # 5
    sigh(force: true)
  end

  error do |lane, exception|
  # This block is called if there was an error running a lane.
  end

  desc "Create ipa"
  lane :build do
    gym
  end


end